config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trackings
  resources :user_trackings, only: :index do
    collection do
      get :image_ad
      get :click_data
      get :event_data
    end
  end  
  # 标签
  namespace :wh_tags do
    resources :page_tags
    resources :base_tags
    resources :pre_tags
  end
  # 标签
  namespace :ad do
    resources :campaigns do
      collection do
        get :event_data_script
        post :save_event_data
        get :get_event_data_script
      end
    end
    resources :creatives
  end

   namespace :cms do
     resources :activities
      resources :activity_details
      resources :articles, except: [:show, :destroy] do
        collection do
          post :upload_image
        end
      end
      resources :jd_tickets, only: [:index] do
        collection do
          get :import_jd_tickets
          post :create_import_jd_tickets
          get :mapping_ticket
          get :jd_activity_details
        end
      end
    end


  namespace :admin do
    resources :employees do
      collection do
        get 'forget_password'
        post 'forget_password'
        get 'reset_mail'
        get 'error_mail'
      end
    end
    resources :trackings do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :vip_tracking
        get :load_detail
      end
    end
    resources :user_trackings, only: :index do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :analysis_tracking
        get :user_analysis
        get :show_details
        get :get_chart
      end
    end
  end

  root to: 'desboard#index'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}

end

app/models/activities/jd_ticket.rb
module Activities
  class JdTicket < ApplicationRecord
    has_one :jdticket_welfare

    enum status: {
      unissued: 0,
      issued: 1
    }
  end
end

app/models/activities/jdticket_welfare.rb
module Activities
  class JdticketWelfare < ApplicationRecord
    belongs_to :order_detail
    belongs_to :activity
    belongs_to :activity_detail
    belongs_to :jd_ticket
    belongs_to :user
    has_one :ticket, as: :mod_entity

    enum status: {
  	    isa_initial: 0,
  	    isa_confirmed: 1,
  	    isa_finished: 2,
  	    isa_deleted: -1
  	  }

  	after_create :ticket_init 

    # 发起人获取首张监测券
    def ticket_init
      Ticket.create(activity_id:self.activity_id,user_id:self.user_id,mod_entity_type:"Activities::JdticketWelfare",mod_entity_id:self.id,ticket_type:2,name:"#{self.denomination}元京东券")
    end  

    def show_package
      self.live_package
    end

    # 匹配发放京东券
    def self.payfor_tickets(activity_id=nil)
    	
    	if activity_id.present?
          welfares = Activities::JdticketWelfare.where(status:["isa_initial","isa_confirmed"],activity_id:activity_id)
    	else
          welfares = Activities::JdticketWelfare.where(status:["isa_initial","isa_confirmed"])
    	end

	    welfares.each do |welfare|
	       order_detail = welfare.order_detail 
	       # 采购订单已收款，或者采购订单已发货
	       if order_detail.ship_done? || order_detail.all_paid?
		      activity_detail = welfare&.activity_detail
		      order_package = order_detail.sum_package.to_f
		      # 如果单位不一致转化单位
		      order_package = order_detail.convert_unit(order_package, order_detail.package_unit, activity_detail&.package_unit, 1).to_f  if activity_detail&.package_unit != order_detail.package_unit
		      denomination,live = activity_detail&.match_package(order_package.to_f)
		        if denomination.present? 
		        	live_package = "#{live.match(/[1-9]\d*/).to_s}#{activity_detail&.package_unit}"
		            Activities::JdticketWelfare.transaction do 
		              jd_ticket = Activities::JdTicket.unissued.where(denomination:denomination).first
		              # 如果有金额匹配的京东券则发放
		              if jd_ticket
		                jd_ticket.update(status:"issued")
		                welfare.update(denomination:denomination,live_package:live_package,jd_ticket_id:jd_ticket.id,card_password:jd_ticket.card_password,status:"isa_finished",expiry_on:jd_ticket.expiry_on) 
		                Ticket.where(mod_entity_type:"Activities::JdticketWelfare",mod_entity_id:welfare.id).update(status:"isa_finished",expiry_on:jd_ticket.expiry_on)
		                test_send_sms(welfare.user.mobile, welfare.user.name, activity_detail&.chemical&.name_cn , denomination)
		              end  
		            end
		        else
		            Activities::JdticketWelfare.transaction do 
		              welfare.update(status:"isa_deleted") 
		              Ticket.where(mod_entity_type:"Activities::JdticketWelfare",mod_entity_id:welfare.id).update(status:"isa_deleted")
		            end  
		        end
		   end     
	    end  
	end

    # 给对应的客户发送提醒短信
	def self.test_send_sms(mobile, user_name, chemical_name , denomination)
	    params = {}
	    params["account"] = 'shyishih'
	    params["pswd"] = 'andy_gxl19841027'
	    params["mobile"] = mobile
	    params["msg"] = "尊敬的#{user_name}，您的#{chemical_name}订单奖励已激活，#{denomination}元京东券可使用了。请登陆会员中心>卡券中心查看。"
	    params["needstatus"] = false
	    url = URI.parse("http://222.73.117.156/msg/HttpBatchSendSM")
	    Net::HTTP.start(url.host, url.port) do |http|
	      req = Net::HTTP::Post.new(url.path)
	      req.set_form_data(params)
	      xml_str =  http.request(req).body
	      response_status = xml_str.split(",")[1]
	      return response_status
	    end
	end


  end
end

app/models/activities/jdticket_welfare_mod.rb
module Activities::JdticketWelfareMod
  extend ActiveSupport::Concern

  included do
    # 活动触发任务
    after_create :jdticket_welfare_init
    after_update :cancel_jdticket_welfare, if: -> { self.detail_status == 7 && Activities::JdticketWelfare.find_by_order_detail_id(self.id) }
  end
  
  # 采购订单创建触发
  def jdticket_welfare_init
    Activity.isa_confirmed.where(category:2).each do |activity|
      activity.activity_details.where(chemical_id:self.chemical_id).each do |activity_detail|
        order_package = self.sum_package
        # 如果单位不一致转化单位
        order_package = convert_unit(order_package, self.package_unit, activity_detail.package_unit, 1)  if activity_detail.package_unit != self.package_unit
        denomination,live = activity_detail.match_package(order_package.to_f)
        if denomination.present?
          live_package = "#{live.match(/[1-9]\d*/).to_s}#{activity_detail.package_unit}"
          Activities::JdticketWelfare.create(activity_id:activity.id,
            activity_detail_id: activity_detail.id,
            user_id:self.customer_order.user_id,
            order_detail_id:self.id,
            denomination: denomination,
            expiry_on:activity.expiry_on,
            live_package:live_package  )
        end
      end
    end
  end

  # 采购订单取消触发
  def cancel_jdticket_welfare
    welfare.update(status:"isa_deleted") 
    Ticket.where(mod_entity_type:"Activities::JdticketWelfare",mod_entity_id:welfare.id,user_id:self.user_id).update(status:"isa_deleted")
  end

end

app/models/activities/testing_order_welfare.rb
module Activities
  class TestingOrderWelfare < ApplicationRecord
    	belongs_to :customer_order
    	belongs_to :activity
      has_many :tickets, as: :mod_entity

    	enum status: {
  	    isa_initial: 0,
  	    isa_confirmed: 1,
  	    isa_finished: 2,
  	    isa_deleted: -1
  	  }

      after_create :ticket_init 

      # 发起人获取首张监测券
      def ticket_init
        Ticket.create(activity_id:1,user_id:self.user_id,mod_entity_type:"Activities::TestingOrderWelfare",mod_entity_id:self.id,expiry_on:self.expiry_on,name:'云检测体验券')
      end

      # 号码兑换
      def self.welfare_ticket(user_id,spread_no)
        welfare = Activities::TestingOrderWelfare.find_by_spread_no(spread_no) 
        head_welfare = Ticket.find_by(mod_entity_type:"Activities::TestingOrderWelfare",mod_entity_id:welfare.id,user_id:user_id) if welfare.present?
        if !welfare.present?
          "请检查您的分享码是否输入正确"
        elsif welfare.user_id == user_id
          "对不起，您不能兑换自己的分享码！"
        elsif head_welfare.present?
          "您已兑换过该分享码，欢迎使用！"
        elsif welfare.spread_times < 3 && welfare.status.in?(["isa_initial","isa_confirmed"])
          Ticket.create(activity_id:1,user_id:user_id,mod_entity_type:"Activities::TestingOrderWelfare",mod_entity_id:welfare.id,expiry_on:welfare.expiry_on,get_ticket_type:1,name:'云检测体验券')
          Ticket.create(activity_id:1,user_id:welfare.user_id,mod_entity_type:"Activities::TestingOrderWelfare",mod_entity_id:welfare.id,expiry_on:welfare.expiry_on,get_ticket_type:2,name:'云检测体验券')
          welfare.spread_times += 1
          welfare.save
          "恭喜您获得了一张检测券，欢迎使用！"
        else
          "您来晚啦！此兑换码已抢兑光~"   
        end
      end
  end    
end

app/models/activities/testing_order_welfare_mod.rb
module Activities::TestingOrderWelfareMod
  extend ActiveSupport::Concern

  included do
    # 活动触发任务
    after_create :testing_order_welfares_init , if: -> { Activity.find(1).isa_confirmed? && self.amount >= 10000 }
    after_update :cancel_order_welfares , if: -> { Activity.find(1).isa_confirmed? && self.amount < 10000 }
  end

  def testing_order_welfares_init
    Activities::TestingOrderWelfare.create(activity_id:1,user_id:self.user_id,customer_order_id:self.id,expiry_on:Activity.find(1).expiry_on,spread_no:([*('A'..'Z'),*('0'..'9')]-%w(0 1 h I O)).sample(4).join )
  end

  def cancel_order_welfares
    welfare = Activities::TestingOrderWelfare.find_by_customer_order_id(self.id)
    if welfare
      self.class.transaction do	
        welfare.update(status:"isa_deleted") 
        Ticket.where(mod_entity_type:"Activities::TestingOrderWelfare",mod_entity_id:welfare.id,user_id:self.user_id).update(status:"isa_deleted")
      end  
    end
  end

end

app/controllers/admin/cms/activities_controller.rb
class Admin::Cms::ActivitiesController < Admin::BaseController
  before_action :set_activity, only: [:edit, :update, :destroy]

  def index
    @activities = ::Activity.where.not(status: :isa_deleted).order(id: :desc).page(params[:page]).per(10)
  end

  def new
    @activity = ::Activity.new
  end

  def edit
  end

  def create
    @activity = ::Activity.create(activity_params)
  end

  def update
    @activity.update(activity_params)
  end

  def destroy
    @activity.update(status: "isa_deleted")
    flash[:success] = "删除成功"
    redirect_to admin_cms_activities_path
  end

  def levels_show_array
    if @field == 'rebate_rules'
      arr = rules[:levels].to_s.split(',')
      arr.map do |p|
        package = p.split('~')
        "#{package[0]}元<=x" + (package[1].blank? ? '' : "< #{package[1]}元" )
      end
    else
      if rules[:package_type].to_i == 0
        arr = rules[:levels].to_s.split(',')
        arr.map do |p|
          package = p.split('~')
          "#{package[0]}#{@price.package_unit}<=x" + (package[1].blank? ? '' : "<#{package[1]}#{@price.package_unit}" )
        end
      else
        rules[:levels].to_s.split(',').map{|p| "#{p}#{@price.package_unit}"}
      end
    end
  end

  def get_cost_price(package)
    packages = ""
    denomination = ""


    return packages,denomination
  end

  private
  def activity_params
    params.require(:activity).permit(:name,
                                     :category,
                                     :activity_mod,
                                     :status,
                                     :base_tags,
                                     :tags,
                                     :describe,
                                     :summary,
                                     :initiator,
                                     :expected_cost,
                                     :actual_cost,
                                     :effect,
                                     :expiry_on,
                                     :start_time,
    )
  end

  def activity_detail_params
    params.require(:activities_activity_detail).permit(:activity_id,
                                            :name,
                                            :chemical_id,
                                            :package,
                                            :package_unit

    )
  end


  def set_activity
    @activity = ::Activity.find params[:id]
  end
end

app/controllers/admin/cms/activity_details_controller.rb
class Admin::Cms::ActivityDetailsController < Admin::BaseController
  before_action :set_activity_detail, only: [:edit, :update, :destroy]

  def index
    @activity = ::Activity.find params[:activity_id]
    @activity_details = @activity.activity_details.default
  end

  def new
    @activity = ::Activity.find params[:activity_id]
    @activity_detail = ActivityDetail.new(activity_id: params[:activity_id])
  end

  def edit
  end

  def create
    @activity_detail = ActivityDetail.create(activity_detail_params)
  end

  def update
    @activity_detail.update(activity_detail_params)
  end

  def destroy
    @activity_detail.update(status: "deleted")
    render 'admin/cms/activity_details/delete'
  end

  private

  def activity_detail_params
    params.require(:activity_detail).permit(:activity_id,
                                            :name,
                                            :chemical_cas,
                                            :packages,
                                            :denomination,
                                            :package_unit

    )
  end


  def set_activity_detail
    @activity_detail = ::ActivityDetail.find params[:id]
  end
end

app/controllers/admin/cms/jd_tickets_controller.rb
class Admin::Cms::JdTicketsController < Admin::BaseController

  def index
    @q = SearchParams.new(params[:search_params])
    search_params = @q.attributes(self)
    @jd_tickets = Activities::JdTicket.default_where(search_params).page(params[:page]).per(10)
  end

  # 导入京东卷页面
  def import_jd_tickets
  end

  def import_error(msg)
    flash[:msg] = msg
    redirect_to action: :index
  end

  # 活动匹配核发京东券
  def mapping_ticket
    Activities::JdticketWelfare.payfor_tickets(params[:activity_id])
  end

  # 京东券活动明细
  def jd_activity_details
    @q = SearchParams.new(params[:search_params] || {activity_id: params[:activity_id]})
    search_params = @q.attributes(self)

    if params[:activity_id].present?
      @activity = Activity.find(params[:activity_id])
    elsif params[:search_params][:activity_id].present?
      @activity = Activity.find(params[:search_params][:activity_id])
    else
      @activity = nil
    end

    if @activity
      @jdticket_welfares = Activities::JdticketWelfare.where(activity_id: @activity.id).includes(:order_detail, :activity, [user: :company]).default_where(search_params)
    else
      @jdticket_welfares = Activities::JdticketWelfare.includes(:order_detail, :activity, [user: :company]).default_where(search_params)
    end

    @wait_payment = @jdticket_welfares.left_joins(:order_detail).where("jdticket_welfares.status in (?) and ( order_details.ship_status = 2 || order_details.payment_status = 1)", [0, 1]).group_by(&:denomination)
    @jd_tickets = Activities::JdTicket.unissued.group_by(&:denomination)

    @jdticket_welfares = @jdticket_welfares.page(params[:page]).per(10)

  end

  # 导入京东券数据
  def create_import_jd_tickets
    time1 = Time.now
    file = params[:attachment][:path]
    #校验文件格式
    import_error("失败，文件格式不正确，请上传.xlsx格式的文件。") and return unless check_file?(file)
    book = Roo::Spreadsheet.open file
    sheet = book.sheet 0

    result_book = Spreadsheet::Workbook.new
    result_sheet = result_book.create_worksheet
    _file_ok = true

      row_num = 0
      error_row = 0
      row_msg = []
      sheet.each_with_index do |row, index|

        @jdticket = _jdticket = Activities::JdTicket.new()
        if index > 0
          jdticket = Activities::JdTicket.find_by(card_id: row[2])
          if jdticket.present?
            row_msg[error_row] = index
            row_num += 1
            error_row += 1
            next
          else
            _jdticket.category = row[0]
            _jdticket.denomination = row[1]
            _jdticket.card_id = row[2]
            _jdticket.card_password = row[3]
            _jdticket.expiry_on = row[4].split("-",).last.gsub(/[\u4e00-\u9fa5]/, '-').to_date
            _jdticket.save
            row_num += 1
          end
        end
      end
      if error_row == 0
        flash[:notice] = "共有" + row_num.to_s + "行，全部导入成功!"
      else
        flash[:success] = "共有" + row_num.to_s + "行，导入成功" + (row_num-error_row).to_s + "行。第" + row_msg.join(",") + "行导入失败,请检查是否已导入。"
      end
    @jd_tickets =  Activities::JdTicket.where(created_at: time1).page(params[:page]).per(10)
    render template: "admin/cms/jd_tickets/index", :locals => { :jd_ticket => @jd_tickets }
  end


  def check_file?(file)
    return false if file.blank?
    file.original_filename =~ /xlsx$/
  end
end

app/views/admin/cms/activities/_edit.html.erb
<%= simple_form_for @activity, url: admin_cms_activity_path(@activity), method: :put, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

  <div class="two fields">
    <%= f.input :name, label: "活动名称" %>
    <%= f.input :category, as: :select, collection: ActivityCategory.pluck(:name,:id), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "活动类型" %>
  </div>

  <div class="two fields">
    <%= f.input :initiator, as: :select, collection: Employee.on_job.pluck(:name,:id), include_blank: '发起人', input_html: {class: 'ui search fluid dropdown '}, label: "活动发起人" %>
    <%= f.input :status, as: :select, collection: select_options_from_enum(::Activity, :status), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "活动状态" %>
  </div>

  <div class="two fields">
    <%= f.input :base_tags, label: "固定标签" %>
    <%= f.input :tags, label: "自定义标签" %>
  </div>

  <div class="two fields">
    <%= f.input :describe, label: "活动描述" %>
    <%= f.input :summary, label: "活动总结" %>
  </div>

  <div class="two fields">
    <%= f.input :expected_cost, label: "预计费用" %>
    <%= f.input :actual_cost, label: "实际费用" %>
  </div>

  <div class="two fields">
    <div class="field">
      <label>开始日期</label>
      <div class="ui calendar J_calendar_datetime" id='calendar1'>
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.input_field :start_time, as: :string %>
        </div>
      </div>
    </div>

    <div class="field">
      <label>结束日期</label>
      <div class="ui calendar J_calendar_datetime" id='calendar2'>
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.input_field :expiry_on, as: :string %>
        </div>
      </div>
    </div>>
  </div>

  <div class="two fields">
    <%= f.input :effect, as: :select, collection: select_options_from_enum(::Activity, :effect), include_blank: '请选择', selected:"请选择",input_html: {class: 'ui dropdown fluid'}, label: "是否达到预期效果" %>
  </div>

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/cms/activities/_list.html.erb
<tr id="activity_<%= activity.id %>">
  <td class="center aligned">
    <%= activity.name %>
  </td>

  <td class="center aligned">
    <%= activity&.category_type&.name %>
    <% if activity.activity_mod == 'Activities::JdticketWelfare' %>
      <%= link_to new_admin_cms_activity_detail_path(activity_id: activity.id), class: 'ui icon popups', remote: true, data: {content: '添加活动规则', variation: 'inverted'} do %>
        <i class="plus icon green"></i>
      <% end %>

      <%= link_to  admin_cms_activity_details_path(activity_id: activity.id), class: 'ui icon popups', data: {content: '查看活动规则详情', variation: 'inverted'}, remote: true do %>
        <i class="tasks icon"></i>
      <% end %>

      <%= link_to  jd_activity_details_admin_cms_jd_tickets_path(activity_id: activity.id), class: 'ui icon popups', data: {content: '京东券活动明细', variation: 'inverted'} do %>
        <i class="book icon"></i>
      <% end %>

    <% end %>
  </td>


  <td class="center aligned">
    <%= activity.i18n_attr_status %>
  </td>

  <td class="center aligned">
    <%= activity.base_tags %>
  </td>

  <td class="center aligned">
    <%= activity.tags %>
  </td>

  <td class="center aligned">
    <%= activity.describe %>
  </td>

  <td class="center aligned">
    <%= activity.summary %>
  </td>

  <td class="center aligned">
    <%= activity.employee&.name %>
  </td>

  <td class="center aligned">
    <%= number_to_currency activity.expected_cost, unit: "￥" %>
  </td>

  <td class="center aligned">
    <%= number_to_currency activity.actual_cost, unit: "￥" %>
  </td>

  <td class="center aligned">
    <%= activity.i18n_attr_effect %>
  </td>

  <td class="center aligned">
    <%= activity.start_time %>
  </td>
  <td class="center aligned">
    <%= activity.expiry_on %>
  </td>

  <td class="center aligned">
    <%= link_to edit_admin_cms_activity_path(activity.id), remote: true, 'data-content' => "修改活动信息", 'data-variation' => 'inverted', class: "ui icon blue basic button" do %>
      <i class="edit icon"></i>
    <% end %>

    <%= link_to admin_cms_activity_path(activity.id), method: :delete, 'data-content' => "删除活动信息", 'data-variation' => 'inverted', class: "ui icon red basic button", data: {confirm: "确定删除吗?"} do %>
      <i class="close icon"></i>
    <% end %>
  </td>

</tr>

app/views/admin/cms/activities/_new.html.erb
<%= simple_form_for @activity, url: admin_cms_activities_path, method: :post, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;"></div>

  <div class="two fields">
    <%= f.input :name, label: "活动名称" %>
    <%= f.input :category, as: :select, collection: ActivityCategory.pluck(:name,:id), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "活动类型" %>
  </div>

  <div class="two fields">
    <%= f.input :initiator, as: :select, collection: Employee.on_job.pluck(:name,:id), include_blank: '发起人', input_html: {class: 'ui search fluid dropdown '}, label: "活动发起人" %>
    <%= f.input :status, as: :select, collection: select_options_from_enum(::Activity, :status), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "活动状态" %>
  </div>

  <div class="two fields">
    <%= f.input :base_tags, label: "固定标签" %>
    <%= f.input :tags, label: "自定义标签" %>
  </div>

  <div class="two fields">
    <%= f.input :describe, label: "活动描述" %>
    <%= f.input :summary, label: "活动总结" %>
  </div>

  <div class="two fields">
    <%= f.input :expected_cost, label: "预计费用" %>
    <%= f.input :actual_cost, label: "实际费用" %>
  </div>

  <div class="two fields">
    <div class="field">
      <label>开始日期</label>
      <div class="ui calendar J_calendar_datetime" id='calendar1'>
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.input_field :start_time, as: :string %>
        </div>
      </div>
    </div>

    <div class="field">
    <label>结束日期</label>
    <div class="ui calendar J_calendar_datetime" id='calendar2'>
      <div class="ui input left icon">
        <i class="calendar icon"></i>
        <%= f.input_field :expiry_on, as: :string %>
      </div>
    </div>
    </div>>
  </div>

  <div class="two fields">
    <%= f.input :effect, as: :select, collection: select_options_from_enum(::Activity, :effect), include_blank: '请选择', selected:"请选择",input_html: {class: 'ui dropdown fluid'}, label: "是否达到预期效果" %>
  </div>

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/cms/activities/create.js.erb
<% if @activity.errors.blank? %>
$("tbody").prepend('<%= j render('list', activity: @activity) %>');
$("#activity_modal").modal('hide');
<% else %>
$(".red.pointing").remove();
$(".field").removeClass('error');
<% @activity.errors.messages.each do |key, value| %>
//parent()方法：返回被选中元素的父元素
$("#activity_<%= key %>").parent().addClass('error');
$("#activity_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
<% end %>
<% end %>

app/views/admin/cms/activities/edit.js.erb
$('#activity_modal').remove();
$('body').append('<div class="ui modal" id="activity_modal"><i class="close icon"></i><h2 class="ui dividing header">修改活动信息</h2><%= j(render 'edit') %></div>');
$('#activity_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();
$('#calendar1').calendar({type: 'date'});
$('#calendar2').calendar({type: 'date'});
$('#initiator').val("<%= @employee&.name %>")

// TODO表单校验
$("#commition").click(function () {
    if ($("#activity_name").val() != "") {
        $("#edit_activity_<%= @activity.id %>").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/cms/activities/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>活动管理</h2>
  </div>
</div>

<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to_with_permissions '新增活动', new_admin_cms_activity_path(), class: 'ui primary button', remote: true %>
      <%= link_to_with_permissions '京东券管理', admin_cms_jd_tickets_path, class: 'ui primary button' %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr>
      <th class="center aligned">活动名称</th>
      <th class="center aligned">活动类型</th>
      <th class="center aligned">活动状态</th>
      <th class="center aligned">固定标签</th>
      <th class="center aligned">自定义标签</th>
      <th class="center aligned">活动描述</th>
      <th class="center aligned">活动总结</th>
      <th class="center aligned">发起人</th>
      <th class="center aligned">预计费用</th>
      <th class="center aligned">实际费用</th>
      <th class="center aligned">是否达到预期效果</th>
      <th class="center aligned">开始日期</th>
      <th class="center aligned">结束日期</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render :partial => "list", :collection => @activities, :as => :activity %>
    </tbody>
  </table>
  <span class="blue">
      <%= page_entries_info(@activities) %>
    </span>
  <%= paginate(@activities, :theme => 'admin') %>
</div>

app/views/admin/cms/activities/new.js.erb
$('#activity_modal').remove();
$('body').append('<div class="ui modal" id="activity_modal"><i class="close icon"></i><h2 class="ui dividing header">添加新活动</h2><%= j(render 'new') %></div>');
$('#activity_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();
$('#calendar1').calendar({type: 'date'});
$('#calendar2').calendar({type: 'date'});


// TODO表单校验
$("#commition").click(function () {
    if ($("#activity_name").val() != "") {
        $("#new_activity").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/cms/activities/update.js.erb
<% if @activity.errors.blank? %>
$("#activity_<%= @activity.id %>").replaceWith("<%= j(render partial: 'list', locals: { activity: @activity} ) %>");
$("#activity_modal").modal('hide');
<% else %>
$(".red.pointing").remove();
$(".field").removeClass('error');
<% @activity.errors.messages.each do |key, value| %>
//parent()方法：返回被选中元素的父元素
$("#activity_<%= key %>").parent().addClass('error');
$("#activity_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
<% end %>
<% end %>