config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trackings
  resources :user_trackings, only: :index do
    collection do
      get :image_ad
      get :click_data
      get :event_data
    end
  end  
  # 标签
  namespace :wh_tags do
    resources :page_tags
    resources :base_tags
    resources :pre_tags
  end
  # 标签
  namespace :ad do
    resources :campaigns do
      collection do
        get :event_data_script
        post :save_event_data
        get :get_event_data_script
      end
    end
    resources :creatives
  end

   namespace :cms do
     resources :activities
      resources :activity_details
      resources :articles, except: [:show, :destroy] do
        collection do
          post :upload_image
        end
      end
      resources :jd_tickets, only: [:index] do
        collection do
          get :import_jd_tickets
          post :create_import_jd_tickets
          get :mapping_ticket
          get :jd_activity_details
        end
      end
    end


  namespace :admin do
    resources :employees do
      collection do
        get 'forget_password'
        post 'forget_password'
        get 'reset_mail'
        get 'error_mail'
      end
    end
    resources :trackings do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :vip_tracking
        get :load_detail
      end
    end
    resources :user_trackings, only: :index do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :analysis_tracking
        get :user_analysis
        get :show_details
        get :get_chart
      end
    end
  end

  root to: 'desboard#index'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}

end

app/models/ad/audience.rb
# 访客
module Ad
  class Audience < ApplicationRecord
    serialize :targeting_ips

  end
end

app/models/ad/baidu_tracking.rb
module Ad
  class BaiduTracking < ApplicationRecord

  	# 每个cookie + 百度唯一链接 的uniq

     def self.load_tracking(load_time=Time.now.yesterday.at_beginning_of_day)
	   # 缓存导入数据库	
	       Ad::UserTracking.where("created_at >= ? and opxurl like '%source=baidu%' ",load_time).each do |message| 
	         tracking = Ad::BaiduTracking.find_by(opxpid:message[:opxpid],opxurl:message[:opxurl]) 
	         if tracking.present? && tracking.disabled != 1
	             tracking.spread_times = tracking.spread_times + 1
               tracking.status = tracking.status + 1 if message[:opxid] > 0 && tracking.status == 0
	             tracking.disabled = 1 if ((Time.now - tracking.time_now).to_f/(60*60*24)).ceil > 14
	             tracking.save
	         else
	           tracking = Ad::BaiduTracking.create(opxpid:message[:opxpid],opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
	         	            opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
	         	            opxuserAgent:message[:opxuserAgent])
	           tracking.spread_times = tracking.spread_times + 1
             tracking.status = tracking.status + 1 if message[:opxid] > 0
	           opxurl_option =  opxurl_analyse(message[:opxurl])
	           tracking.cas = opxurl_option["cas"]
	           tracking.active_id = opxurl_option["active_id"]
	           tracking.keyword = opxurl_option["keyword"]
	           tracking.source = opxurl_option["source"]
	           tracking.plan = opxurl_option["plan"]
	           tracking.unit = opxurl_option["unit"]
	           tracking.ly = opxurl_option["ly"]
	           tracking.e_matchtype = opxurl_option["e_matchtype"]
	           tracking.e_creative = opxurl_option["e_creative"]
	           tracking.e_adposition = opxurl_option["e_adposition"]
	           tracking.e_pagenum = opxurl_option["e_pagenum"]
	           tracking.e_keywordid = opxurl_option["e_keywordid"]
	           tracking.save
	         end    
	       end  
           
         # 客户为百度带来的首次注册转化
	       register_conversion

	       # 客户为百度带来的询盘转化
	       inquiry_conversion

	       # 客户为百度带来的订单转化
	       order_conversion
	 end


   # 客户为百度带来的首次注册转化
	 def self.register_conversion
       Ad::BaiduTracking.where("opxid = 0 and disabled != 1 ").each do |message| 
         user  = User.find_by(opxpid:message.opxpid)
       	 opxid = user.present? ? user.id : Ad::UserTracking.where("opxpid = ? and opxid > 0",message.opxpid).last&.opxid
       	 
       	 if opxid 

       	   user = User.find_by(id:opxid) 
       	   message.opxid = user&.id

       	   unless user.opxpid
       	     user.update(opxpid:message[:opxpid]) 
       	     message.status = message.status + 1

             if message.time_now <= user.created_at
                Ad::ConversionMapping.create(opxpid:message[:opxpid],opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
         	                   opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
         	                   opxuserAgent:message[:opxuserAgent],conversion_times:1,cas:message[:cas],active_id:message[:active_id],
         	                   keyword:message[:keyword],source:message[:source],status:message[:status],tracking_type:"Ad::BaiduTracking",
         	                   tracking_id:message.id,mapping_type:"User",mapping_id:user.id)
                message.status = message.status + 10
             end
           end  

         end

         message.disabled = 1 if ((Time.now - message.time_now).to_f/(60*60*24)).ceil > 14
         message.save

       end
	 end


	 # 客户为百度带来的询盘转化
	 def self.inquiry_conversion
       Ad::BaiduTracking.where("status < 100 and disabled != 1 and opxid > 0 and cas is not null").each do |message| 

       	 chemical = Chemical.find_by(cas:message.cas)

         inquiry = Inquiry.where("user_id = ? and chemical_id = ? and created_at >= ?",message.opxid , chemical.id , message.time_now).last
         if inquiry.present? 
            Ad::ConversionMapping.create(opxpid:message[:opxpid],opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
     	                   opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
     	                   opxuserAgent:message[:opxuserAgent],conversion_times:1,cas:message[:cas],active_id:message[:active_id],
     	                   keyword:message[:keyword],source:message[:source],status:message[:status],tracking_type:"Ad::BaiduTracking",
     	                   tracking_id:message.id,mapping_type:"Inquiry",mapping_id:inquiry.id)
            message.status = message.status + 100
            message.save
         end

       end
	 end



	 # 客户为百度带来的订单转化
	 def self.order_conversion
       Ad::BaiduTracking.where("status < 1000 and disabled != 1 and opxid > 0 and cas is not null").each do |message| 
         chemical = Chemical.find_by(cas:message.cas)
         
         order_detail = OrderDetail.where("user_id = ? and chemical_id = ? and created_at >= ?",message.opxid ,chemical.id , message.time_now).last
         if order_detail.present? 
            Ad::ConversionMapping.create(opxpid:message[:opxpid],opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
     	                   opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
     	                   opxuserAgent:message[:opxuserAgent],conversion_times:1,cas:message[:cas],active_id:message[:active_id],
     	                   keyword:message[:keyword],source:message[:source],status:message[:status],tracking_type:"Ad::BaiduTracking",
     	                   tracking_id:message.id,mapping_type:"OrderDetail",mapping_id:order_detail.id)
            message.status = message.status + 1000
            message.save
         end

       end
	 end


   # 解析百度参数
   # 例子："http://www.whmall.com/products/407-25-0.html?source=baidu&plan=爆品推广&unit=三氟乙酸酐&keyword=三氟乙酸干&ly=PC&e_matchtype=1&e_creative=21057998872&e_adposition=clg1&e_pagenum=1&e_keywordid=81813623744"
	 def self.opxurl_analyse(opxurl)
       result = {}
       option = opxurl.split("/").last
       cas = option.split(".html?").first
       result["cas"] = cas
       options = option.split(".html?").last
       options.split("&").each do |op|
       	  opt = op.split("=")
          result[opt[0]] = opt[1]
       end
       return result
	 end
	 

  end
end

app/models/ad/campaign.rb
# 广告计划
module Ad
  class Campaign < ApplicationRecord
  	has_many :creatives

    serialize :base_tags
    serialize :pre_tags
    serialize :city
    serialize :products
    
    before_save :set_tags

    has_many :exposure_das
    has_many :click_das
    has_many :event_das

    enum status: {
      isa_initial: 0,   #默认状态
      isa_confirmed: 1, #开启
      isa_stop: 2,  #暂停
      isa_deleted: -1   #关闭
    }

	  def set_tags
	    self.pre_tags = self.pre_tags.to_s.split(" ")
	    self.base_tags = self.base_tags.to_s.split(" ")
	  end

  	# 返回转化追踪的js代码
  	def event_tracking_script(evrnt_no)
      %Q(
       <script type="text/javascript" async>
          document.write(unescape("%3Cscript src='/user_trackings/event_data?evrnt_no=#{evrnt_no}&campaign_id=#{self.id}" + "&opxtitle=" + opxtitle + "&opxurl=" + opxurl + "&opxreferrer=" + opxreferrer + "&opxid=" + opxid + "&opxuserAgent=" + opxuserAgent + "' type='text/javascript'%3E%3C/script%3E"));
       </script>
      )
    end

  	def show_tag
      self.base_tags + self.pre_tags
  	end

    # 宽高匹配最合适的创意
  	def ad_size_match(width,height,ad_type=0)
      match_creatives = self.creatives
      cap_creatives = []
      match_creatives.each do |ad|
      	ad = ad.ad_size
        ad_size = ad.split("*")
        cap_width = ad_size[0].to_i - width.to_i 
        cap_height = ad_size[1].to_i - height.to_i 
        cap_creatives << cap_width.to_i + cap_height.to_i
      end
      cap_index = cap_creatives.index(cap_creatives.min)
      match_creatives[cap_index]
  	end
	 
  end
end

app/models/ad/click_da.rb
# 广告点击
module Ad
  class ClickDa < ApplicationRecord

  	def self.load_tracking
      cache_read("user_uuids_list").each do |_| 
        messages = cache_read("#{_}_click_url_list")
	      messages.each do |message|
          if message
             Ad::ClickDa.create(opxpid:_,opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
                                 opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
                                 opxuserAgent:message[:opxuserAgent],campaign_id:message[:campaign_id],creative_id:message[:creative_id]) 
          end
        end  if messages
	      Rails.cache.delete("#{_}_click_url_list")
      end if cache_read("user_uuids_list").present?
  	end

  end
end

app/models/ad/conversion_mapping.rb
# 转化纪录
module Ad
  class ConversionMapping < ApplicationRecord
	 
  end
end

app/models/ad/creative.rb
# 广告创意
module Ad
  class Creative < ApplicationRecord

    belongs_to :campaign
    has_many :attachments, as: :attachment_entity
    accepts_nested_attributes_for :attachments, allow_destroy: true

    enum status: {
      isa_initial: 0,   #默认状态
      isa_confirmed: 1, #开启
      isa_finished: 2,  #暂停
      isa_deleted: -1   #关闭
    }

    enum ad_size: {
      "200*200": 0,   
      "250*250": 1, 
      "300*250": 2,  
      "320*250": 3,
      "336*280": 4,
      "468*60": 5,
      "600*90": 6,
      "728*90": 7,
      "950*90": 8,  
      "960*90": 9,
      "1000*90": 10
    }

    enum ad_type: {
      image: 0,   #默认状态图片
      flash: 1  #动画
    }

  end
end

app/models/ad/event_da.rb
# 广告转化
module Ad
  class EventDa < ApplicationRecord

  	def self.load_tracking
      cache_read("user_uuids_list").each do |_| 
        messages = cache_read("#{_}_event_url_list")
	      messages.each do |message|
          if message
             Ad::EventDa.create(opxpid:_,opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
                                 opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
                                 opxuserAgent:message[:opxuserAgent],campaign_id:message[:campaign_id],creative_id:message[:creative_id],event_no:message[:event_no]) 
          end
        end  if messages
	      Rails.cache.delete("#{_}_event_url_list")
      end if cache_read("user_uuids_list").present?
  	end

  end
end

app/models/ad/exposure_da.rb
# 广告曝光
module Ad
  class ExposureDa < ApplicationRecord

  	def self.load_tracking
      cache_read("user_uuids_list").each do |_| 
          messages = cache_read("#{_}_exposure_url_list")
          messages.each do |message|
  	        if message
  	           Ad::ExposureDa.create(opxpid:_,opxid:message[:opxid],time_now:message[:time_now],domain:message[:domain],
  		         	                   opxtitle:message[:opxtitle],opxreferrer:message[:opxreferrer],opxurl:message[:opxurl],ip:message[:ip],
  		         	                   opxuserAgent:message[:opxuserAgent],campaign_id:message[:campaign_id],creative_id:message[:creative_id]) 
  	        end
  	      end if messages   
	        Rails.cache.delete("#{_}_exposure_url_list")
      end if cache_read("user_uuids_list").present?
  	end

  end
end

app/controllers/admin/ad/campaigns_controller.rb
class Admin::Ad::CampaignsController < Admin::BaseController

  before_action :set_campaign, only: [:show, :edit, :update, :destroy, :event_data_script,:save_event_data,:get_event_data_script]	

  def index
  	@q = SearchParams.new(params[:search_params])
    search_params = @q.attributes(self)
    @campaigns =  ::Ad::Campaign.default_where(search_params).order(id: :desc).page(params[:page]).per(10)
  end

  def new
    @campaign = ::Ad::Campaign.new
  end

  def edit

  end

  def create
    @campaign = ::Ad::Campaign.create(campaign_params)
  end

  def update
    @campaign.update(campaign_params)
  end

  def destroy
    @campaign.update(status:-1)
  end

  def show

  end

  # 设置获取转化代码节点
  def event_data_script

  end
  def save_event_data
    @campaign.update(params_event)
  end
  def get_event_data_script
    @event_no = params[:event_no]
  end

  private

  def set_campaign
    @campaign = ::Ad::Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:ad_campaign).permit(:name,
                                     :activity_id,
                                     :client_id,
                                     :status,
                                     :base_tags,
                                     :pre_tags,
                                     :products,
                                     :city,
                                     :start_time,
                                     :end_time,
                                     :describe,
                                     :expected_cost
    )
  end

  def params_event
    params.require(:ad_campaign).permit(:event_1,
                                        :event_2,
                                        :event_3,
                                        :event_4,
                                        :event_5,
                                        :event_6
    )
  end

end

app/controllers/admin/ad/creatives_controller.rb
class Admin::Ad::CreativesController < Admin::BaseController

  before_action :set_creative, only: [:show, :edit, :update, :destroy]	
  before_action :set_campaign, only: [:new, :show, :edit, :destroy]  

  def index
  	@q = SearchParams.new(params[:search_params])
    search_params = @q.attributes(self)
    @campaign_id = search_params["campaign.name"].present? ? ::Ad::Campaign.find_by(name:search_params["campaign.name"])&.id : params[:campaign_id]
    search_params[:campaign_id] = @campaign_id
    @campaign = ::Ad::Campaign.find(@campaign_id)
    @creatives =  ::Ad::Creative.default_where(search_params).order(id: :desc).page(params[:page]).per(10)
  end

  def new
    @creative = ::Ad::Creative.new
    @attachment = @creative.attachments.last || @creative.attachments.new
  end

  def edit
    @attachments = @creative.attachments
  end

  def create
    @creative = ::Ad::Creative.create(creative_params)
    @campaign = @creative.campaign
  end

  def update
    @creative.update(creative_params)
    @campaign = @creative.campaign
  end

  def destroy
    @creative.update(status:-1)
  end

  def show

  end

  private

  def set_creative
    @creative = ::Ad::Creative.find(params[:id])
  end

  def set_campaign
    @campaign = ::Ad::Campaign.find(params[:campaign_id])
  end

  def creative_params
    p = params.require(:ad_creative).permit(:name,
                                     :campaign_id,
                                     :ad_size,
                                     :link,
                                     :status,
                                     attachments_attributes: [:path]
    )

    p[:link] = "http://#{p[:link]}" if p[:link].present? && p[:link] !~ /^http/
    p

  end

end

app/views/admin/ad/creatives/_edit.html.erb
<%= simple_form_for @creative, url: admin_ad_creative_path(@creative), method: :put, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;"></div>
  <%= f.hidden_field :campaign_id, value: @campaign.id %>

    <% @attachments.compact.each do |att| %>
       <%= link_to att.name, att.path.url %>  <br/>
    <% end %>

  <div class="two fields">
    <%= f.fields_for 'attachments', @creative.attachments.new  do |fa| %>
        <%= fa.input :path %>
    <% end %>
  </div>

  <div class="two fields">
    <%= f.input :name, label: "创意名称" %>
    <%= f.input :link, label: "跳转链接" %>
  </div>

  <div class="two fields">
    <%= f.input :ad_size, as: :select, collection: select_options_from_enum(::Ad::Creative, :ad_size), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "创意尺寸" %>
    <%= f.input :status, as: :select, collection: select_options_from_enum(::Ad::Creative, :status), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "状态" %>
  </div>

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/ad/creatives/_list.html.erb
<tr id="creative_<%= creative.id %>">
  <td class="center aligned">
    <%= @campaign.name %> 
  </td>

   <td class="center aligned">
    <%= creative.name %> 
  </td>

  <td class="center aligned">
     <%= creative.link %> 
  </td>

  <td class="center aligned">
    图片
  </td>

  <td class="center aligned">
     <%= creative.ad_size %> 
  </td>

  <td class="center aligned">
    <%= creative.i18n_attr_status %>
  </td>

  <td class="center aligned">
    <%= link_to edit_admin_ad_creative_path(creative.id,campaign_id:@campaign.id), remote: true, 'data-content' => "修改创意", 'data-variation' => 'inverted', class: "ui icon blue basic button" do %>
      <i class="edit icon"></i>
    <% end %>

    <%= link_to admin_ad_creative_path(creative.id,campaign_id:@campaign.id), method: :delete, remote: true, 'data-content' => "删除创意", 'data-variation' => 'inverted', class: "ui icon red basic button", data: {confirm: "确定删除吗?"} do %>
      <i class="close icon"></i>
    <% end %>
  </td>

</tr>

app/views/admin/ad/creatives/_new.html.erb
<%= simple_form_for @creative, url: admin_ad_creatives_path, method: :post, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;"></div>
  <%= f.hidden_field :campaign_id, value: @campaign.id %>

  <div class="two fields">
    <%= f.fields_for 'attachments', @attachment  do |fa| %>
        <%= fa.input :path %>
    <% end %>
  </div>

  <div class="two fields">
    <%= f.input :name, label: "创意名称" %>
    <%= f.input :link, label: "跳转链接" %>
  </div>

  <div class="two fields">
    <%= f.input :ad_size, as: :select, collection: select_options_from_enum(::Ad::Creative, :ad_size), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "创意尺寸" %>
    <%= f.input :status, as: :select, collection: select_options_from_enum(::Ad::Creative, :status), include_blank: false, input_html: {class: 'ui dropdown fluid'}, label: "状态" %>
  </div>
  

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/ad/creatives/_search_form.html.erb
<% if @q.present? %>
  <div class="ui blue segment">
    <%= simple_form_for @q, url: admin_ad_creatives_path, method: :get, wrapper: 'semantic_search_form' do |f| %>
      <div class="ui five column grid">
        <%= f.input "campaign.name", placeholder: '广告计划名称' %>
        <%= f.input :name, placeholder: '创意名称' %>
        <%= f.input :link, placeholder: '跳转链接' %>
        <%= f.input :ad_size, placeholder: '创意尺寸' %>
        <div class="column">
          <%= f.submit '搜索', class: 'ui primary button' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/ad/creatives/create.js.erb
<% if @creative.errors.blank? %>
  $("tbody").prepend('<%= j render('list', creative: @creative) %>');
  $("#creative_modal").modal('hide');
<% else %>
  $(".red.pointing").remove();
  $(".field").removeClass('error');
  <% @creative.errors.messages.each do |key, value| %>
	//parent()方法：返回被选中元素的父元素
	$("#creative_<%= key %>").parent().addClass('error');
	$("#creative_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>

app/views/admin/ad/creatives/destroy.js.erb
window.location.reload();

app/views/admin/ad/creatives/edit.js.erb
$('#creative_modal').remove();
$('body').append('<div class="ui modal" id="creative_modal"><i class="close icon"></i><h2 class="ui dividing header">修改广告计划</h2><%= j(render 'edit') %></div>');
$('#creative_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();
$('#calendar1').calendar({type: 'date'});
$('#calendar2').calendar({type: 'date'});
$('#initiator').val("<%= @employee&.name %>")

// TODO表单校验
$("#commition").click(function () {
    if ($("#ad_creative_name").val() != "") {
        $("#edit_ad_creative_<%= @creative.id %>").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/ad/creatives/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a><%= @campaign&.name %>：广告创意管理</h2>
  </div>
</div>

<div class="ui grid">
  <div class="left floated  wide column">
    <%= render partial: 'search_form' %>
  </div>
</div>

<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to_with_permissions '新增广告创意', new_admin_ad_creative_path(campaign_id:@campaign.id), class: 'ui primary button', remote: true %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr>
      <th class="center aligned">广告名称</th>
      <th class="center aligned">创意名称</th>
      <th class="center aligned">跳转链接</th>
      <th class="center aligned">类型</th>
      <th class="center aligned">尺寸</th>
      <th class="center aligned">状态</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render :partial => "list", :collection => @creatives, :as => :creative %>
    </tbody>
  </table>
  <span class="blue">
      <%= page_entries_info(@creatives) %>
    </span>
  <%= paginate(@creatives, :theme => 'admin') %>
</div>

app/views/admin/ad/creatives/new.js.erb
$('#creative_modal').remove();
$('body').append('<div class="ui modal" id="creative_modal"><i class="close icon"></i><h2 class="ui dividing header">添加新广告计划</h2><%= j(render 'new') %></div>');
$('#creative_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();
$('#calendar1').calendar({type: 'date'});
$('#calendar2').calendar({type: 'date'});


// TODO表单校验
$("#commition").click(function () {
    if ($("#ad_creative_name").val() != "") {
        $("#new_ad_creative").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/ad/creatives/update.js.erb
<% if @creative.errors.blank? %>
  $("#creative_<%= @creative.id %>").replaceWith("<%= j(render partial: 'list', locals: { creative: @creative} ) %>");
  $("#creative_modal").modal('hide');
<% else %>
  $(".red.pointing").remove();
  $(".field").removeClass('error');
  <% @creative.errors.messages.each do |key, value| %>
    //parent()方法：返回被选中元素的父元素
    $("#creative_<%= key %>").parent().addClass('error');
    $("#creative_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>