config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trackings
  resources :user_trackings, only: :index do
    collection do
      get :image_ad
      get :click_data
      get :event_data
    end
  end  
  # 标签
  namespace :wh_tags do
    resources :page_tags
    resources :base_tags
    resources :pre_tags
  end
  # 标签
  namespace :ad do
    resources :campaigns do
      collection do
        get :event_data_script
        post :save_event_data
        get :get_event_data_script
      end
    end
    resources :creatives
  end

   namespace :cms do
     resources :activities
      resources :activity_details
      resources :articles, except: [:show, :destroy] do
        collection do
          post :upload_image
        end
      end
      resources :jd_tickets, only: [:index] do
        collection do
          get :import_jd_tickets
          post :create_import_jd_tickets
          get :mapping_ticket
          get :jd_activity_details
        end
      end
    end


  namespace :admin do
    resources :employees do
      collection do
        get 'forget_password'
        post 'forget_password'
        get 'reset_mail'
        get 'error_mail'
      end
    end
    resources :trackings do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :vip_tracking
        get :load_detail
      end
    end
    resources :user_trackings, only: :index do
      collection do
        get :analysis
        get :delete_tracking
        get :hot_analysis
        get :analysis_tracking
        get :user_analysis
        get :show_details
        get :get_chart
      end
    end
  end

  root to: 'desboard#index'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}

end

app/models/page_tag.rb
class PageTag < ApplicationRecord

  enum status: {
    isa_actived: 1, #激活状态
    isa_deleted: -1   #关闭
  }

  def parent
    self.parent_id ? PageTag.find_by(id:self.parent_id) : self
  end

  def parents
    PageTag.where("parent_id is null")
  end
  
end

app/controllers/admin/wh_tags/base_tags_controller.rb
class Admin::WhTags::BaseTagsController < Admin::BaseController

end

app/controllers/admin/wh_tags/page_tags_controller.rb
class Admin::WhTags::PageTagsController < Admin::BaseController

  before_action :set_page_tag, only: [:show, :edit, :update, :destroy]	

  def index
  	@q = SearchParams.new(params[:search_params])
    search_params = @q.attributes(self)
    @page_tags =  PageTag.default_where(search_params).order(id: :desc).page(params[:page]).per(10)
  end

  def new
    @page_tag = PageTag.new
  end

  def edit

  end

  def create
    @page_tag = PageTag.create(page_params)
  end

  def update
    @page_tag.update(page_params)
  end

  def destroy
    @page_tag.update(status:-1)
  end

  def show
  	@base_tag = BaseTag.find_by(name:@page_tag.name)
    @base_users = @base_tag.my_tags
    @pre_tag = PreTag.find_by(name:@page_tag.name)
    @pre_users = @pre_tag.my_tags
  end

  private

  def set_page_tag
    @page_tag = PageTag.find(params[:id])
  end

  def page_params
    params.require(:page_tag).permit(:name,
                                     :parent_id,
                                     :page_type,
                                     :status,
                                     :base_name,
                                     :page_url,
                                     :status
    )
  end




end

app/controllers/admin/wh_tags/pre_tags_controller.rb
class Admin::WhTags::PreTagsController < Admin::BaseController

end

app/views/admin/wh_tags/page_tags/_edit.html.erb
<%= simple_form_for @page_tag, url: admin_wh_tags_page_tag_path, method: :put, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;"></div>

  <div class="two fields">
    <%= f.input :base_name, label: "专题名称" %>
    <%= f.input :page_type, as: :select, collection: ["前台客户","后台员工"], include_blank: '统计类型', input_html: {class: 'ui search fluid dropdown '}, label: "统计类型" %>
  </div>

  <div class="two fields">
    <%= f.input :name, label: "名称" %>
    <%= f.input :page_url, label: "页面链接" %>
  </div>

  <div class="two fields">
    <%= f.input :status, as: :select, collection: select_options_from_enum(PageTag, :status), include_blank: '请选择',input_html: {class: 'ui search dropdown fluid'}, label: "状态" %>
    <%= f.input :parent_id, as: :select, collection:PageTag.where("parent_id is null")&.map{|_|[_.name,_.id]}, include_blank: '请选择', input_html: {class: 'ui search fluid dropdown '}, label: "父标签" %>
  </div>

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/wh_tags/page_tags/_list.html.erb
<tr id="page_tag_<%= page_tag.id %>">
  <td class="center aligned">
    <%= page_tag.base_name %>
  </td>

  <td class="center aligned">
    <%= page_tag.name %>
  </td>

  <td class="center aligned">
    <%= page_tag.page_type %>
  </td>

  <td class="center aligned">
    <%= page_tag.page_url %>
  </td>

  <td class="center aligned">
    <%= page_tag.i18n_attr_status %>
  </td>

  <td class="center aligned">
    <%= page_tag.parent&.name %>
  </td>

  <td class="center aligned">
    <%= page_tag.updated_at.to_date %>
  </td>

  <td class="center aligned">
    <%= link_to edit_admin_wh_tags_page_tag_path(page_tag.id), remote: true, 'data-content' => "修改标签", 'data-variation' => 'inverted', class: "ui icon blue basic button" do %>
      <i class="edit icon"></i>
    <% end %>

    <%= link_to admin_wh_tags_page_tag_path(page_tag.id), method: :delete, remote: true, 'data-content' => "关闭标签", 'data-variation' => 'inverted', class: "ui icon red basic button", data: {confirm: "确定删除吗?"} do %>
      <i class="close icon"></i>
    <% end %>
  </td>

</tr>

app/views/admin/wh_tags/page_tags/_new.html.erb
<%= simple_form_for @page_tag, url: admin_wh_tags_page_tags_path, method: :post, remote: true do |f| %>
  <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;"></div>

  <div class="two fields">
    <%= f.input :base_name, label: "专题名称" %>
    <%= f.input :page_type, as: :select, collection: ["前台客户","后台员工"], include_blank: '统计类型', selected:"前台客户", input_html: {class: 'ui search fluid dropdown '}, label: "统计类型" %>
  </div>

  <div class="two fields">
    <%= f.input :name, label: "名称" %>
    <%= f.input :page_url, label: "页面链接" %>
  </div>

  <div class="two fields">
    <%= f.input :status, as: :select, collection: select_options_from_enum(PageTag, :status), include_blank: '请选择',input_html: {class: 'ui dropdown fluid'}, label: "状态" %>
    <%= f.input :parent_id, as: :select, collection:PageTag.where("parent_id is null")&.map{|_|[_.name,_.id]}, include_blank: '请选择', input_html: {class: 'ui search fluid dropdown '}, label: "父标签" %>
  </div>

  <div class="field">
    <div class="actions ">
      <div class="ui button primary" id="commition">提交</div>
      <div class="ui cancel button">取消</div>
    </div>
  </div>

<% end %>

app/views/admin/wh_tags/page_tags/_search_form.html.erb
<% if @q.present? %>
  <div class="ui blue segment">
    <%= simple_form_for @q, url: admin_wh_tags_page_tags_path, method: :get, wrapper: 'semantic_search_form' do |f| %>
      <div class="ui five column grid">
        <%= f.input :base_name, placeholder: '专题名称' %>
        <%= f.input :name, placeholder: '名称' %>
        <%= f.input :parent_id, as: :select, collection:PageTag.where("parent_id is null")&.map{|_|[_.name,_.id]}, include_blank: '请选择父标签', input_html: {class: 'ui search fluid dropdown '}, label: "父标签" %>
        <div class="column">
          <%= f.submit '搜索', class: 'ui primary button' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/wh_tags/page_tags/create.js.erb
<% if @page_tag.errors.blank? %>
$("tbody").prepend('<%= j render('list', page_tag: @page_tag) %>');
$("#page_tag_modal").modal('hide');
<% else %>
$(".red.pointing").remove();
$(".field").removeClass('error');
<% @page_tag.errors.messages.each do |key, value| %>
//parent()方法：返回被选中元素的父元素
$("#page_tag_<%= key %>").parent().addClass('error');
$("#page_tag_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
<% end %>
<% end %>

app/views/admin/wh_tags/page_tags/destroy.js.erb
<% if @page_tag.errors.blank? %>
$("#page_tag_<%= @page_tag.id %>").replaceWith("<%= j(render partial: 'list', locals: { page_tag: @page_tag} ) %>");
$("#page_tag_modal").modal('hide');
<% else %>
$(".red.pointing").remove();
$(".field").removeClass('error');
<% @page_tag.errors.messages.each do |key, value| %>
//parent()方法：返回被选中元素的父元素
$("#page_tag_<%= key %>").parent().addClass('error');
$("#page_tag_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
<% end %>
<% end %>

app/views/admin/wh_tags/page_tags/edit.js.erb
$('#page_tag_modal').remove();
$('body').append('<div class="ui modal" id="page_tag_modal"><i class="close icon"></i><h2 class="ui dividing header">修改活动信息</h2><%= j(render 'edit') %></div>');
$('#page_tag_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();
$('#calendar1').calendar({type: 'date'});
$('#calendar2').calendar({type: 'date'});
$('#initiator').val("<%= @employee&.name %>")

// TODO表单校验
$("#commition").click(function () {
    if ($("#page_tag_page_url").val() != "") {
        $("#edit_page_tag_<%= @page_tag.id %>").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/wh_tags/page_tags/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>页面标签管理</h2>
  </div>
</div>

<div class="ui grid">
  <div class="left floated  wide column">
    <%= render partial: 'search_form' %>
  </div>
</div>

<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to_with_permissions '新增标签', new_admin_wh_tags_page_tag_path(), class: 'ui primary button', remote: true %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr>
      <th class="center aligned">专题名称</th>
      <th class="center aligned">名称</th>
      <th class="center aligned">统计类型</th>
      <th class="center aligned">页面链接</th>
      <th class="center aligned">标签状态</th>
      <th class="center aligned">父标签</th>
      <th class="center aligned">创建时间</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render :partial => "list", :collection => @page_tags, :as => :page_tag %>
    </tbody>
  </table>
  <span class="blue">
      <%= page_entries_info(@page_tags) %>
    </span>
  <%= paginate(@page_tags, :theme => 'admin') %>
</div>

app/views/admin/wh_tags/page_tags/new.js.erb
$('#page_tag_modal').remove();
$('body').append('<div class="ui modal" id="page_tag_modal"><i class="close icon"></i><h2 class="ui dividing header">添加标签</h2><%= j(render 'new') %></div>');
$('#page_tag_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();


// TODO表单校验
$("#commition").click(function () {
    if ($("#page_tag_page_url").val() != "") {
        $("#new_page_tag").submit();
    } else {
        $("#form_message").text("请完善信息！").show(200);
    }
});

app/views/admin/wh_tags/page_tags/update.js.erb
<% if @page_tag.errors.blank? %>
$("#page_tag_<%= @page_tag.id %>").replaceWith("<%= j(render partial: 'list', locals: { page_tag: @page_tag} ) %>");
$("#page_tag_modal").modal('hide');
<% else %>
$(".red.pointing").remove();
$(".field").removeClass('error');
<% @page_tag.errors.messages.each do |key, value| %>
//parent()方法：返回被选中元素的父元素
$("#page_tag_<%= key %>").parent().addClass('error');
$("#page_tag_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
<% end %>
<% end %>